### ISSUE TITLE
As a content editor, I would like to be able to define my keywords in the SEO extension.

### ISSUE THREAD

**Issue by ghost** [bobdenotter/seo#1]
Keywords are still considered an important part of seo. Adding a field that accepts n number of comma separated keywords would be a useful addition to this extension.

This can be a single text field, requires no update to the Google Snippet and produces a single html tag as follows:

`<meta name="keywords" content="<INPUT>" />`

The ideal would be that this is included in the output of `{{ seo.metatags() }}`.

**Comment by bobdenotter** [comment]
Not that i'm questioning the logic behind this, but I thought the keywords were pretty much completely ignored altogether. Do you have any light reading on this matter? :-)

**Comment by ghost** [comment]
I have done some reading around this myself, just to confirm some of my theories and the assumption this feature request was built upon. Based on the Google 2015 guidelines, Keywords are no longer searched in meta tags, leaving only the following as relevant entities:

https://support.google.com/webmasters/answer/79812

I think it would be acceptable to close this feature request, under the pretence that arguably the most used search engine does not support them. For the tags the extension doesn't currently support (e.g: Google verification) this could be an opportunity for future releases.

**Comment by errogaht** [comment]
Hello!
In my case i can't use this extension because not only google in the world, users use another SE also.
For example in Russia its impossible to describe why SEO extension dont contains keywords field, beacause Google just have a piece of all Russian traffic

**Comment by errogaht** [comment]
thankyou!
