### ISSUE TITLE
As a content editor, I would like to be able to define my charset in the SEO extension.

### ISSUE THREAD

**Issue by ghost** [bobdenotter/seo#2]
Inline with Google SEO guidelines it is useful to denote the charset of your webpage. This could be a useful function for the SEO extension. 

https://support.google.com/webmasters/bin/answer.py?hl=en&answer=79812

**Comment by Intendit** [comment]
Isn't the charset the same on every page of a site and therefore something that shouldn't be in the editor, but rather defined in the theme?

**Comment by bobdenotter** [comment]
As @Intendit mentions.. Do you have an example of a page that uses a different charset on different parts of the site. Seems like a hassle for the maintainers. :-)

**Comment by ghost** [comment]
Having done some research, yes, charset is consistent throughout pages :)

**Comment by bobdenotter** [comment]
Ok, closing this issue, then. :-)
