### ISSUE TITLE
Ability to edit og:type

### ISSUE THREAD

**Issue by jackiboy** [bobdenotter/seo#22]
Hi Bob.

Can we please have the ability to edit the og:type

`<meta property="og:type" content="website">`

[http://ogp.me/#types](OG:Types)

**Comment by michaelborn** [comment]
@bobdenotter Would this be something you'd accept a pull request on? Any problems you see with a potential implementation?

**Comment by bobdenotter** [comment]
Hi @mborn319, 

Yes, I'll happily accept a PR for that. 👍 

It's something i've not needed myself, so never got around to implementing it. If you do though, that's great! :-)
