### ISSUE TITLE
Override _metatags.twig

### ISSUE THREAD

**Issue by beunoit** [bobdenotter/seo#27]
Hi !
I am trying to override _metatags.twig by putting a copy in my theme folder, but it ignore my override.
Have I to put it in a sub folder in my theme ?
I want to do this to add a default share image when the condition "if image" is empty.
Maybe it could be an idea to add this parameter in the config file ?
best regards

**Comment by jasperjorna** [comment]
Did you enable the override in `app/config/extensions/seo.bobdenotter.yml`?

```
templates:
    meta: _metatags.twig
```

**Comment by beunoit** [comment]
Thanks a lot ! You are right !
