### ISSUE TITLE
[BUG] HTTP response printed before seo tags

### ISSUE THREAD

**Issue by artggd** [bobdenotter/seo#37]
Since my last composer update, calling `{{ seo.metatags() }}` prints the first chars of an HTTP response, like so: `HTTP/1.0 200 OK Cache-Control: no-cache`

I am using the following versions:
- bolt/bolt: dev-release/3.3
- bobdenotter/seo: v0.11.0

This seems to be due to [this commit](https://github.com/bolt/bolt/commit/0e5b8bc2fcc368b0c59e6b50c81ac5f3fb3c71db) on bolt core; Bolt's `render` service now uses TemplateResponse instead of the former BoltResponse. TemplateResponse is meant to return an HTTP response (not an HTML bit), thus printing that string at the start of the SEO tags.

Using `twig`service instead of `render` [here](https://github.com/bobdenotter/seo/blob/master/src/SEO.php#L237) would fix it. Though I shall not come with a PR because the commit causing the bug might sound like a bit of a BC break. 

I let you guys decide whether it should be fixed on bolt core or this repository (or both) 🙂

**Comment by artggd** [comment]
To clarify, the difference between BoltResponse and TemplateResponse lies in their __toString() method.
Both classes extend Symfony HttpFoundation Response, BoltResponse overrides the __toString() but TemplateResponse does not and returns its parent's __toString(). That guy prints the HTTP string ([here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Response.php#L280))

**Comment by bobdenotter** [comment]
I have seen this pop up before, but I couldn't yet put my finger on it. Thanks! 👍 

Feel free to PR it for sweet github Karma points, because I don't think we'll revert it in Bolt itself. :-)

**Comment by artggd** [comment]
Sweet as! I will 😃
