### ISSUE TITLE
Doesn't work in Bolt 3.3

### ISSUE THREAD

**Issue by siada** [bobdenotter/seo#49]
This commit: https://github.com/bolt/bolt/commit/1807ffe432ca5e01f24f38ae0504e5464b6d8a0b causes this extension to no longer work with 3.3-beta (as of beta-3 an onwards) as the SeoField implements FieldInterface not FieldTypeInterface

**Comment by bobdenotter** [comment]
I am out of town until July 4th, so I won't be able to take a look in the meantime. I'll do so, when I get back, unless somebody makes a PR before that time.

**Comment by siada** [comment]
I've created a PR to move SeoField to FieldTypeBase, which fixes this for bolt 3.3 but I'm unsure if this will break for below 3.3?

**Comment by peterboorsma** [comment]
Same problem here. @siada Your fix works on my 3.3.0 beta installs. A quick test with Bolt 3.2.11  was also positive.

**Comment by bobdenotter** [comment]
@peter which site is this? I used 1.0.1 on Vlieland yesterday, and I was certain it worked.
