### ISSUE TITLE
Default Meta Description when field is type of "repeater"

### ISSUE THREAD

**Issue by develth** [bobdenotter/seo#60]
Hey there, 

if the meta Description is not set on a ContentType, it outputs the following:

`<meta name="description" content="Doctrine\Common\Collections\ArrayCollection@00000000611a067f00007fb879bd1fc2"/>
`

It seems to have a problem working together with the field type "repeater".

**Comment by xiaohutai** [comment]
I can't seem to reproduce this (Bolt 3.4.5). Can you still consistently reproduce this one?

**Comment by develth** [comment]
i made a PR that is already merged:

https://github.com/bobdenotter/seo/pull/61
